flowchart TD
    dot[pezkuwichain.io] --> devhub[pezkuwi_sdk_docs]

    devhub --> pezkuwi_sdk
    devhub --> reference_docs
    devhub --> guides
	devhub --> external_resources

    pezkuwi_sdk --> substrate
    pezkuwi_sdk --> frame
    pezkuwi_sdk --> xcm
	pezkuwi_sdk --> templates
